config/routes.rb
Rails.application.routes.draw do

  resources :rol_usuarios
  resources :rols
  resources :orden_entregas
  resources :orden_productos do
    member do
      put :update_cantidad
      get :delete_item
    end
  end  

  resources :orden_proyectos
  resources :ordens do
    collection do
      post :carrito
      get :carrito
      get :confirmar
    end
  end
  resources :clientes
  resources :productos do 
    member do
      get :comprar
    end
    collection do 
      get :filter
    end
  end
  
  resources :categoria
  devise_for :users
  resources :proyectos
  root "landpage#index"

  get 'admin/users', to: "landpage#users"
  
  get 'admin/users/:id/show', to: "landpage#users_show"
  get 'admin/users/:id/edit', to: "landpage#users_edit" 
  get 'admin/users/:id/destroy', to: "landpage#users_destroy"     
  
  get 'landpage/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorium.rb
class Categorium < ApplicationRecord
  validates :nombre, 
  :imagen, presence:true

  validates :nombre, 
  length: {minimum:3, maximum: 50}

  validates :nombre,
    uniqueness: true
    
  def nproductos
    return Producto
    .where(categorium_id: self.id)
    .count
  end  
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :ordens
  belongs_to :user
  
  def full_name
    return "#{self.nombres} #{self.apell_pat} #{self.apell_mat}"
  end
end

app/models/orden.rb
class Orden < ApplicationRecord
  belongs_to :cliente
  has_many :orden_producto
  has_many :orden_entrega

  def get_total 
    t = 0
    self.orden_producto.each do |u| 
      t = t + (u.precio * u.cantidad)
    end
    return t
  end
  
  def proceso_text
    if self.proceso.year == 2016 and 
      self.proceso.month == 10 and
      self.proceso.day == 30
      return "---"
    else
      return self.proceso
    end
  end

  def entrega_text
    if self.entrega.year == 2016 and 
      self.entrega.month == 10 and
      self.entrega.day == 30
      return "---"
    else
      return self.entrega
    end
  end

  def cierre_text
    if self.cierre.year == 2016 and 
      self.cierre.month == 10 and
      self.cierre.day == 30
      return "---"
    else
      return self.cierre
    end
  end

end

app/models/orden_entrega.rb
class OrdenEntrega < ApplicationRecord
  belongs_to :orden
end

app/models/orden_producto.rb
class OrdenProducto < ApplicationRecord
  belongs_to :orden
  belongs_to :producto

  validates :cantidad, numericality: {message: "ingrese un numero valido"}
end

app/models/orden_proyecto.rb
class OrdenProyecto < ApplicationRecord
  belongs_to :orden
  belongs_to :proyecto
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :categorium
  
  validates :nombre, 
  :descripcion, :imagen, presence: { message: "Este campo es requerido."}

  validates :nombre, 
  uniqueness: { message: "ya ha sido utilizado. Escriba otro."}

   validates :nombre, 
  length: { minimum: 4, maximum: 100, 
  message: "el nombre debe estar entre 4 y 100 caracteres"}

  validates :descripcion, 
  length: { minimum:15, maximum: 200,
  message: "la descripcion debe estar entre 15 y 200 caracteres"}

 
  
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
end

app/models/rol.rb
class Rol < ApplicationRecord
  
end

app/models/rol_usuario.rb
class RolUsuario < ApplicationRecord
  belongs_to :user
  belongs_to :rol
end

app/models/user.rb
class User < ApplicationRecord
  after_save :enlazar_a_cliente 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable

  def enlazar_a_cliente
    cl = Cliente.where(user_id: self.id).first
    if cl.blank?
      cl = Cliente.new
      cl.user_id = self.id
      cl.nombres = "---"
      cl.apell_pat = "---"
      cl.apell_mat = "---"
      cl.nif = "---"
      cl.save
    end
  end
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy]

  layout 'admin'
  
  # GET /proyectos
  # GET /proyectos.json
  def index
    @proyectos = Proyecto.all
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end

  # GET /proyectos/1/edit
  def edit
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(proyecto_params)

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully created.' }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
    respond_to do |format|
      if @proyecto.update(proyecto_params)
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto.destroy
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: 'Proyecto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proyecto_params
      params.require(:proyecto).permit(:nombre, :imagen)
    end
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: %i[ show edit update destroy ]

  # GET /rols or /rols.json
  def index
    @rols = Rol.all
  end

  # GET /rols/1 or /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols or /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: "Rol was successfully created." }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1 or /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: "Rol was successfully updated." }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1 or /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url, notice: "Rol was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rol_params
      params.require(:rol).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/landpage_helper.rb
module LandpageHelper
end

app/helpers/ordens_helper.rb
module OrdensHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/rol_usuarios_helper.rb
module RolUsuariosHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/views/proyectos/_form.html.erb
<%= form_with(model: proyecto) do |form| %>
  <% if proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
        <% proyecto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.text_field :imagen %>
  </div>

  <div class="actions">
    <%= form.submit("Guardar", {class: "btn btn-primary"}) %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Actualizar Proyecto</h1>

      <%= render 'form', proyecto: @proyecto %>

      <%= link_to 'Mostrar detalles', @proyecto,
        class: "btn btn-primary mb-4" %> |
      <%= link_to 'Volver', proyectos_path,
        class: "btn btn-secondary mb-4" %>
    </div>
  </div>
</div>

app/views/proyectos/index.html.erb
<link href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css"
rel="stylesheet" >

<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"><%= notice %></p>

      <h1>Proyectos</h1>

      <table id="myTable" class="table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Imagen</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @proyectos.each do |proyecto| %>
            <tr>
              <td><%= proyecto.nombre %></td>
              <td><%= proyecto.imagen %></td>
              <td><%= link_to 'Mostrar', proyecto,
                class: "btn btn-primary" %></td>
              <td><%= link_to 'Editar', edit_proyecto_path(proyecto), 
                class: "btn btn-secondary" %></td>
              <td><%= link_to 'Eliminar', proyecto,
                method: :delete, 
                data: { confirm: 'Estas seguro?' },
                class:"btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'Nuevo Proyecto', new_proyecto_path,
      class:"btn btn-primary mb-4" %>

      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

      <script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

      <script type="text/javascript">
          $(document).ready(function(){
          $('#myTable').DataTable({
            language: {
              url: "//cdn.datatables.net/plug-ins/1.11.3/i18n/es-cl.json"
            }
          });
        });
      </script>
    </div>
  </div>
</div>

app/views/proyectos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Nuevo Proyecto</h1>

      <%= render 'form', proyecto: @proyecto %>

      <%= link_to 'Volver', proyectos_path, 
        class: "btn btn-secondary mb-4" %>
    </div>
  </div>
</div>

app/views/proyectos/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p>
        <strong>Nombre:</strong>
        <%= @proyecto.nombre %>
      </p>

      <p>
        <strong>Imagen:</strong>
        <%= @proyecto.imagen %>
      </p>

      <%= link_to 'Editar', edit_proyecto_path(@proyecto),
      class: "btn btn-primary mb-4" %> |
      <%= link_to 'Volver', proyectos_path,
      class: "btn btn-secondary mb-4" %>
    </div>
  </div>
</div>