config/routes.rb
Rails.application.routes.draw do

  resources :rol_usuarios
  resources :rols
  resources :orden_entregas
  resources :orden_productos do
    member do
      put :update_cantidad
      get :delete_item
    end
  end  

  resources :orden_proyectos
  resources :ordens do
    collection do
      post :carrito
      get :carrito
      get :confirmar
    end
  end
  resources :clientes
  resources :productos do 
    member do
      get :comprar
    end
    collection do 
      get :filter
    end
  end
  
  resources :categoria
  devise_for :users
  resources :proyectos
  root "landpage#index"

  get 'admin/users', to: "landpage#users"
  
  get 'admin/users/:id/show', to: "landpage#users_show"
  get 'admin/users/:id/edit', to: "landpage#users_edit" 
  get 'admin/users/:id/destroy', to: "landpage#users_destroy"     
  
  get 'landpage/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/orden_producto.rb
class OrdenProducto < ApplicationRecord
  belongs_to :orden
  belongs_to :producto

  validates :cantidad, numericality: {message: "ingrese un numero valido"}
end

app/controllers/orden_productos_controller.rb
class OrdenProductosController < ApplicationController
  before_action :set_orden_producto, only: [:show, :edit, :update, :destroy ]

  # GET /orden_productos or /orden_productos.json
  def index
    @orden_productos = OrdenProducto.all
  end

  # GET /orden_productos/1 or /orden_productos/1.json
  def show
  end

  # GET /orden_productos/new
  def new
    @orden_producto = OrdenProducto.new
  end

  # GET /orden_productos/1/edit
  def edit
  end

  # POST /orden_productos or /orden_productos.json
  def create
    @orden_producto = OrdenProducto.new(orden_producto_params)

    respond_to do |format|
      if @orden_producto.save
        format.html { redirect_to @orden_producto, notice: "Orden producto was successfully created." }
        format.json { render :show, status: :created, location: @orden_producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @orden_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orden_productos/1 or /orden_productos/1.json
  def update
    respond_to do |format|
      if @orden_producto.update(orden_producto_params)
        format.html { redirect_to @orden_producto, notice: "Orden producto was successfully updated." }
        format.json { render :show, status: :ok, location: @orden_producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @orden_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orden_productos/1 or /orden_productos/1.json
  def destroy
    @orden_producto.destroy
    respond_to do |format|
      format.html { redirect_to orden_productos_url, notice: "Orden producto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_item
  op = OrdenProducto.find(params[:id])
  op.destroy
  redirect_to "/ordens/carrito", flash: {notice: "Producto quitado del carrito."}
  end

  def update_cantidad
    op = OrdenProducto.find(params[:id])
    op.cantidad = params[:cantidad]
    if op.valid?
      op.save
     redirect_to "/ordens/carrito", flash: {notice: "Cantidad actualizada."}
    else
      redirect_to "/ordens/carrito", flash: 
      {alert: op.
      errors.full_messages.join("<br>")}
    end
    
    return
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orden_producto
      @orden_producto = OrdenProducto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def orden_producto_params
      params.require(:orden_producto).permit(:orden_id, :producto_id, :cantidad, :precio, :instrucciones, :descuento)
    end
end

app/helpers/orden_productos_helper.rb
module OrdenProductosHelper
end

app/views/orden_productos/_form.html.erb
<%= form_with(model: orden_producto) do |form| %>
  <% if orden_producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orden_producto.errors.count, "error") %> prohibited this orden_producto from being saved:</h2>

      <ul>
        <% orden_producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :orden_id %>
    <%= form.text_field :orden_id %>
  </div>

  <div class="field">
    <%= form.label :producto_id %>
    <%= form.text_field :producto_id %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.number_field :cantidad %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio %>
  </div>

  <div class="field">
    <%= form.label :instrucciones %>
    <%= form.text_field :instrucciones %>
  </div>

  <div class="field">
    <%= form.label :descuento %>
    <%= form.text_field :descuento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orden_productos/edit.html.erb
<h1>Editar Orden Producto</h1>

<%= render 'form', orden_producto: @orden_producto %>

<%= link_to 'Mostrar', @orden_producto, class: "btn btn-primary mb-4" %> 
<%= link_to 'Volver', orden_productos_path, class: "btn btn-secondary mb-4" %>

app/views/orden_productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orden Productos</h1>

<table>
  <thead>
    <tr>
      <th>Orden</th>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Precio</th>
      <th>Instrucciones</th>
      <th>Descuento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orden_productos.each do |orden_producto| %>
      <tr>
        <td><%= orden_producto.orden_id %></td>
        <td><%= orden_producto.producto_id %></td>
        <td><%= orden_producto.cantidad %></td>
        <td><%= orden_producto.precio %></td>
        <td><%= orden_producto.instrucciones %></td>
        <td><%= orden_producto.descuento %></td>
        <td><%= link_to 'Mostrar', orden_producto %></td>
        <td><%= link_to 'Editar', edit_orden_producto_path(orden_producto) %></td>
        <td><%= link_to 'Eliminar', orden_producto, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Orden Producto', new_orden_producto_path, class: "btn btn-primary mb-4" %>

app/views/orden_productos/new.html.erb
<h1>New Orden Producto</h1>

<%= render 'form', orden_producto: @orden_producto %>

<%= link_to 'Volver', orden_productos_path %>

app/views/orden_productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Orden:</strong>
  <%= @orden_producto.orden_id %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @orden_producto.producto_id %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @orden_producto.cantidad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @orden_producto.precio %>
</p>

<p>
  <strong>Instrucciones:</strong>
  <%= @orden_producto.instrucciones %>
</p>

<p>
  <strong>Descuento:</strong>
  <%= @orden_producto.descuento %>
</p>

<%= link_to 'Editar', edit_orden_producto_path(@orden_producto) %> |
<%= link_to 'Volver', orden_productos_path %>