config/routes.rb
Rails.application.routes.draw do

  resources :rol_usuarios
  resources :rols
  resources :orden_entregas
  resources :orden_productos do
    member do
      put :update_cantidad
      get :delete_item
    end
  end  

  resources :orden_proyectos
  resources :ordens do
    collection do
      post :carrito
      get :carrito
      get :confirmar
    end
  end
  resources :clientes
  resources :productos do 
    member do
      get :comprar
    end
    collection do 
      get :filter
    end
  end
  
  resources :categoria
  devise_for :users
  resources :proyectos
  root "landpage#index"

  get 'admin/users', to: "landpage#users"
  
  get 'admin/users/:id/show', to: "landpage#users_show"
  get 'admin/users/:id/edit', to: "landpage#users_edit" 
  get 'admin/users/:id/destroy', to: "landpage#users_destroy"     
  
  get 'landpage/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorium.rb
class Categorium < ApplicationRecord
  validates :nombre, 
  :imagen, presence:true

  validates :nombre, 
  length: {minimum:3, maximum: 50}

  validates :nombre,
    uniqueness: true
    
  def nproductos
    return Producto
    .where(categorium_id: self.id)
    .count
  end  
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :ordens
  belongs_to :user
  
  def full_name
    return "#{self.nombres} #{self.apell_pat} #{self.apell_mat}"
  end
end

app/models/orden.rb
class Orden < ApplicationRecord
  belongs_to :cliente
  has_many :orden_producto
  has_many :orden_entrega

  def get_total 
    t = 0
    self.orden_producto.each do |u| 
      t = t + (u.precio * u.cantidad)
    end
    return t
  end
  
  def proceso_text
    if self.proceso.year == 2016 and 
      self.proceso.month == 10 and
      self.proceso.day == 30
      return "---"
    else
      return self.proceso
    end
  end

  def entrega_text
    if self.entrega.year == 2016 and 
      self.entrega.month == 10 and
      self.entrega.day == 30
      return "---"
    else
      return self.entrega
    end
  end

  def cierre_text
    if self.cierre.year == 2016 and 
      self.cierre.month == 10 and
      self.cierre.day == 30
      return "---"
    else
      return self.cierre
    end
  end

end

app/models/orden_entrega.rb
class OrdenEntrega < ApplicationRecord
  belongs_to :orden
end

app/models/orden_producto.rb
class OrdenProducto < ApplicationRecord
  belongs_to :orden
  belongs_to :producto

  validates :cantidad, numericality: {message: "ingrese un numero valido"}
end

app/models/orden_proyecto.rb
class OrdenProyecto < ApplicationRecord
  belongs_to :orden
  belongs_to :proyecto
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :categorium
  
  validates :nombre, 
  :descripcion, :imagen, presence: { message: "Este campo es requerido."}

  validates :nombre, 
  uniqueness: { message: "ya ha sido utilizado. Escriba otro."}

   validates :nombre, 
  length: { minimum: 4, maximum: 100, 
  message: "el nombre debe estar entre 4 y 100 caracteres"}

  validates :descripcion, 
  length: { minimum:15, maximum: 200,
  message: "la descripcion debe estar entre 15 y 200 caracteres"}

 
  
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
end

app/models/rol.rb
class Rol < ApplicationRecord
  
end

app/models/rol_usuario.rb
class RolUsuario < ApplicationRecord
  belongs_to :user
  belongs_to :rol
end

app/models/user.rb
class User < ApplicationRecord
  after_save :enlazar_a_cliente 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable

  def enlazar_a_cliente
    cl = Cliente.where(user_id: self.id).first
    if cl.blank?
      cl = Cliente.new
      cl.user_id = self.id
      cl.nombres = "---"
      cl.apell_pat = "---"
      cl.apell_mat = "---"
      cl.nif = "---"
      cl.save
    end
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :authenticate_user!, except: [:filter, :show] 
  before_action :set_producto, only: %i[ show edit update destroy ]

  layout "admin", except: [:filter, :comprar]

  def initialize
    super
    @categorias = Categorium.all
  end

  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end
    
  def filter
    @productos = Producto.all
  end
  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
   
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: "Producto was successfully created." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: "Producto was successfully updated." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: "Producto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def comprar
    @producto = Producto.find(params[:id])
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:nombre, :categorium_id,
      :descripcion,
      :imagen)
    end
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: %i[ show edit update destroy ]

  # GET /rols or /rols.json
  def index
    @rols = Rol.all
  end

  # GET /rols/1 or /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols or /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: "Rol was successfully created." }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1 or /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: "Rol was successfully updated." }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1 or /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url, notice: "Rol was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rol_params
      params.require(:rol).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/landpage_helper.rb
module LandpageHelper
end

app/helpers/ordens_helper.rb
module OrdensHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/rol_usuarios_helper.rb
module RolUsuariosHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/views/productos/_form.html.erb
<%= form_with(model: producto) do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.text_field :imagen %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :categorium_id %>
    <select name="producto[categorium_id]">
      <% @categorias.each do |t| %>
      <option value="<%= t.id %>"><%= t.nombre %></option>
      <% end %>  
    </select>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/productos/comprar.html.erb
<div class= "container">
  <div class ="row">
    <div class="col">
      <h1><%= @producto.nombre %></h1>
      <img class="img-fluid" src= "<%= @producto.imagen %>">
    </div>
    <div class="col">
      <p><%= @producto.descripcion %></p>

      <form action="/ordens/carrito" method="POST">
      <%= hidden_field_tag :authenticity_token, 
          form_authenticity_token %>

      <%= hidden_field_tag :producto_id, @producto.id %>    
      
      <div class="mt-4 mb-4"> 
        <%= label_tag(:cantidad, "Cantidad:") %>
        <%= number_field_tag :cantidad, 
          nil, min: 1, max: 99, required: true %>
      </div>
      
      <button type="submit" 
        class="btn btn-primary">Anadir al carrito
      </button>
      </form>
    </div>
  </div>
 </div> 

app/views/productos/edit.html.erb
<h1>Editar Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Mostrar', @producto, class: "btn btn-primary mb-4" %> |
<%= link_to 'Volver', productos_path, class: "btn btn-secondary mb-4" %>

app/views/productos/filter.html.erb
<div class= "container">
  <div class= "row">
    <% @productos.each_with_index do |t| %>
      <div class="col-3">
        <div class="card mt-4">
          <img src="<%= t.imagen %>"
           class="card-img-top" alt="<%= t.nombre %>">
          <div class="card-body">
            <h5 class="card-title"><%= t.nombre %></h5>
            <p class="card-text"><%= t.descripcion %></p>
            <a href="/productos/<%= t.id %>/comprar" class="btn btn-primary">Comprar</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/productos/index.html.erb
<link href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css"
rel="stylesheet" >
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<table id="myTable" class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Categoria</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.categorium.nombre %></td>
        <td><%= link_to 'Mostrar', producto, class: "btn btn-primary mb-4" %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto), class:"btn btn-secondary"  %></td>
        <td><%= link_to 'Eliminar', producto, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Producto', new_producto_path, class: "btn btn-primary" %>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">
    $(document).ready(function(){
    $('#myTable').DataTable({
      language: {
        url: "//cdn.datatables.net/plug-ins/1.11.3/i18n/es-cl.json"
      }
    });
  });
</script>

app/views/productos/new.html.erb
<h1>Nuevo Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Volver', productos_path, class: "btn btn-secondary mb-4" %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @producto.categorium.nombre %>
</p>

<%= link_to 'Editar', edit_producto_path(@producto), class: "btn btn-primary mb-4" %> |
<%= link_to 'Volver', productos_path, class: "btn btn-secondary mb-4" %>